### ISSUE TITLE
cloud deploy fails while fetching cluster name

### ISSUE THREAD

**Issue by jeevanullas** [eucalyptus/eucalyptus-cookbook#136]
Trying to deploy a distributed cloud and it fails. Following are the details:

bootstrap.json -> http://paste.fedoraproject.org/177468/14225307/raw/

The environment is http://paste.fedoraproject.org/177467/25306791/raw/

Using motherbrain it gives the following error:

http://paste.fedoraproject.org/177475/33290142/raw/

Using the testing branch. No idea what is causing this, any help would be appreciated.

Cheers,
Deependra

**Comment by viglesiasce** [comment]
@jeevanullas is the environment uploaded to the server? Can you do ```knife environment info eucalyptus-default```

**Comment by jeevanullas** [comment]
Hi @viglesiasce , please find below the environment:

# knife environment show eucalyptus-default

chef_type:           environment
cookbook_versions:
  apt:                       = 2.3.10
  boost:                     = 0.2.0
  build-essential:           = 2.0.6
  cassandra:                 = 0.2.4
  ceph-deploy:               = 0.1.0
  chef_handler:              = 1.1.6
  dmg:                       = 2.2.2
  erlang:                    = 1.5.6
  eucalyptus:                = 0.3.19
  git:                       = 3.1.0
  install_from:              = 3.0.4
  iptables:                  = 0.14.1
  java:                      = 1.29.0
  metachef:                  = 3.0.4
  midokura:                  = 0.2.0
  ntp:                       = 1.7.0
  packagecloud:              = 0.0.16
  python:                    = 1.4.6
  riak:                      = 2.4.20
  riak-cs:                   = 2.2.10
  riak-cs-create-admin-user: = 0.4.0
  riak-cs-ssl:               = 0.2.1
  riakcs-cluster:            = 0.1.0
  runit:                     = 1.5.14
  selinux:                   = 0.8.0
  sysctl:                    = 0.4.0
  thrift:                    = 1.2.0
  ulimit:                    = 0.3.2
  volumes:                   = 3.0.4
  windows:                   = 1.36.1
  xfs:                       = 1.1.0
  yum:                       = 3.5.2
  yum-epel:                  = 0.6.0
  yum-erlang_solutions:      = 0.2.0
default_attributes:
  eucalyptus:
    euca2ools-repo:  http://release-repo.eucalyptus-systems.com/releases/euca2ools/3.2/centos/6/x86_64
    eucalyptus-repo: http://release-repo.eucalyptus-systems.com/releases/eucalyptus/4.1/centos/6/x86_64/
    network:
      bridge-interface:  br0
      bridged-nic:       em1
      config-json:
        Clusters:
          Subnet:
            Gateway:    10.104.0.1
            Name:       10.104.0.0
            Netmask:    255.255.0.0
            PrivateIps: 10.104.3.26-10.104.3.50
            Subnet:     10.104.0.0
        InstanceDnsDomain:  eucalyptus.internal
        InstanceDnsServers: 10.104.10.1
        PublicIps:          10.104.3.1-10.104.3.25
      mode:              EDGE
      private-interface: br0
      public-interface:  br0
    topology:
      clc-1:       10.104.10.1
      clusters:
        default:
          cc-1:            10.104.10.28
          das-device:      vg01
          nodes:           10.104.10.66
          sc-1:            10.104.10.28
          storage-backend: das
      riakcs:
        access-key: SZJS2MJUWTWG-RAWT1NI
        endpoint:   10.111.5.79
        secret-key: tqDnzXioGCMHRWPAv1E-W6RvEcsYKyLsY5gaRA==
      user-facing: 10.104.10.1
    yum-options:     --nogpg
description:         Default environment file for installing Eucalyptus.
json_class:          Chef::Environment
name:                eucalyptus-default
override_attributes:

**Comment by jeevanullas** [comment]
This issue is not there anymore. The problem seems to be happening because of chef version. Once I reverted back to chef 11 on both client and server everything seems to have worked (I also had to do mb purge).

Perhaps we should look at updating the README.md with what version of chef this cookbook works? Just a thought.
