### ISSUE TITLE
fast installer - unable to use pool.ntp.org

### ISSUE THREAD

**Issue by jdcaddie13** [eucalyptus/eucalyptus-cookbook#156]
Encountering an issue running the fast installer, its bombing out at the ntpdate -u command. The issue is that ntp.pool* is being blocked from my lab. The ability to set the ntp server in the fast install would be great.

Work around >>
Placed and entry in /etc/hosts pointing to my internal ntp server

**Comment by viglesiasce** [comment]
This is now configurable. Fixed by https://github.com/eucalyptus/eucalyptus-cookbook/pull/153
