### ISSUE TITLE
Faststart tutorials need to be updated for 4.2.0 conventions

### ISSUE THREAD

**Issue by tbeckham** [eucalyptus/eucalyptus-cookbook#237]
The faststart tutorials scripts use eucarc. They need to stop using eucarc and be updated to use current euca2ools methodologies to get credentials and perform cloud interactions.

https://github.com/eucalyptus/eucalyptus-cookbook/blob/master/faststart/tutorials/launch-instances.sh
https://github.com/eucalyptus/eucalyptus-cookbook/blob/master/faststart/tutorials/install-image.sh
https://github.com/eucalyptus/eucalyptus-cookbook/blob/master/faststart/tutorials/describe-images.sh

**Comment by hspencer77** [comment]
@tbeckham , FYI, after talking with @mbacchi , it looks like using ```eval `clcadmin-assume-system-credentials` ``` and ```eval `euare-releaserole` ``` will not fix these scripts.  We will need to leverage creating a euca2ools configuration file for the eucalyptus/admin user, then modify these tutorial scripts to check for that file. From there, the ```--region {username}@{region}``` will be utilized.  Does this make sense?

**Comment by tbeckham** [comment]
Yep makes sense. Make it so.

**Comment by lincolnthomas** [comment]
With the creds and eucarc and euca-... commands going away in 4.3, this become a requirement for 4.3 release?

**Comment by tbeckham** [comment]
@lincolnthomas I'm not sure what you are asking here. The tutorials have been updated this ticket should be closed now. There are still a form of a credential file now, it is just in the form of ini file instead of eucarc. In addition, it is created differently and its contents/format are different as well. With regard to "euca-" commands they are not going away. What *IS* going away in 4.3 are euca admin commands. Those are not used here anymore either.
