### ISSUE TITLE
In VPCMIDO mode, the bridge (br0) created on NCs does not need physical NICs attached.

### ISSUE THREAD

**Issue by nephomaniac** [eucalyptus/eucalyptus-cookbook#314]
In VPCMIDO mode, the bridge (br0) created on NCs does not need physical NICs attached. Currently the same procedure to create the bridge, attach em1 to it, and move the network configuration to br0 (which is required in EDGE mode) is done in VPCMIDO. In VPCMIDO all VM networking is provided by MidoNet, and there is no need for br0 to have access to physical network. In VPCMIDO mode, br0 should be just created. This can also address the midolman problems we are observing.

**Comment by mbacchi** [comment]
Fixed in Pull Request #326 and also Pull Request #328
