### ISSUE TITLE
FastInstall run with CentOS 7 but the Document is not updated

### ISSUE THREAD

**Issue by landall** [eucalyptus/eucalyptus-cookbook#361]
Fastinstall is updated to Eucalyptus 4.3 with CentOS 7, however README.md says CentOS 6.

And why it must run with CentOS 7?

**Comment by mbacchi** [comment]
@landall Eucalyptus 4.3 was updated to use systemd vs. SysV init.  This is why RHEL/CentOS 7 is required for 4.3 and above.

I will update the README shortly to correct this oversight.
